# 1. Library Import

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
%matplotlib inline

import matplotlib as mpl  # 기본 설정
import matplotlib.pyplot as plt  # 그래프 그리기
import matplotlib.font_manager as fm  # 폰트 관리


!apt-get update -qq         # apt-get 패키지 설치 명령어, -qq : 에러외 메세지 숨기기
!apt-get install fonts-nanum* -qq #나눔글꼴 설치

fe = fm.FontEntry(fname=r'/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic') #파일 저장되어있는 경로와 이름 설정
fm.fontManager.ttflist.insert(0, fe)  # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 10, 'font.family': 'NanumGothic'}) #폰트설정

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package fonts-nanum.
(Reading database ... 123595 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Selecting previously unselected package fonts-nanum-coding.
Preparing to unpack .../fonts-nanum-coding_2.5-3_all.deb ...
Unpacking fonts-nanum-coding (2.5-3) ...
Selecting previously unselected package fonts-nanum-eco.
Preparing to unpack .../fonts-nanum-eco_1.000-7_all.deb ...
Unpacking fonts-nanum-eco (1.000-7) ...
Selecting previously unselected package fonts-nanum-extra.
Preparing to unpack .../fonts-nanum-extra_20200506-1_all.deb ...
Unpacking fonts-nanum-extra (20200506-1) ...
Setting up fonts-nanum-extra (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Setting up fonts-nanum-coding (2.5-3) ...
Setting up fonts-nanum-eco (1.000-7) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...

# 2. 데이터 불러오기 및 확인

In [ ]:
df_hitter = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/hitter_salary_allyears.csv')
hitter = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/hitter_salary.csv')

In [ ]:
df_hitter.head()

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,팀,연봉(만원),WAR
0,4,최형우,KIA,0.300,136,555,456,65,137,31,...,0.485,0.413,0.898,38,0.263,0.000,2020,KIA,"150,000",6.59
1,5,김동한,롯데,0.282,42,85,78,9,22,4,...,0.333,0.333,0.666,5,0.167,0.222,2020,롯데,"4,500",-0.24
2,23,김준태,롯데,0.159,43,104,88,10,14,3,...,0.193,0.275,0.468,1,0.222,0.000,2020,롯데,"3,800",2.18
3,14,김문호,롯데,0.243,51,109,103,6,25,7,...,0.311,0.269,0.580,6,0.095,0.182,2020,한화,"5,000",-0.30
4,20,한동희,롯데,0.203,59,207,187,12,38,9,...,0.283,0.271,0.554,6,0.114,0.500,2020,롯데,"4,700",2.74

In [8]:
salary = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/Salary_WAR.csv')
for i in range(19,24):
  globals()['stats_20' + str(i)] = pd.read_csv(f'/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/kbo_player_stats_full20{i}.csv')

In [4]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4205 entries, 0 to 4204
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수      4205 non-null   object
 1   연도      4205 non-null   int64
 2   팀       4205 non-null   object
 3   연봉(만원)  4205 non-null   object
 4   WAR     4205 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 164.4+ KB

In [18]:
salary.rename(columns={'선수':'선수명'},inplace=True)

In [21]:
salary.rename(columns={'팀':'팀명'},inplace=True)

In [19]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4205 entries, 0 to 4204
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수명     4205 non-null   object
 1   연도      4205 non-null   int64
 2   팀       4205 non-null   object
 3   연봉(만원)  4205 non-null   object
 4   WAR     4205 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 164.4+ KB

In [11]:
salary['연도'].unique()

array([2020, 2021, 2022, 2023, 2024])

In [5]:
# 연봉 데이터타입 int로 변경
salary['연봉(만원)']  = salary['연봉(만원)'].str.replace(',','').astype('int64')

In [9]:
stats_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      293 non-null    int64
 1   선수명     293 non-null    object
 2   팀명      293 non-null    object
 3   AVG     271 non-null    float64
 4   G       293 non-null    int64
 5   PA      293 non-null    int64
 6   AB      293 non-null    int64
 7   R       293 non-null    int64
 8   H       293 non-null    int64
 9   2B      293 non-null    int64
 10  3B      293 non-null    int64
 11  HR      293 non-null    int64
 12  TB      293 non-null    int64
 13  RBI     293 non-null    int64
 14  SAC     293 non-null    int64
 15  SF      293 non-null    int64
 16  BB      293 non-null    int64
 17  IBB     293 non-null    int64
 18  HBP     293 non-null    int64
 19  SO      293 non-null    int64
 20  GDP     293 non-null    int64
 21  SLG     271 non-null    float64
 22  OBP     271 non-null    float64
 23  OPS     271 non-null    float64
 24  MH      293 non-null    int64
 25  RISP    293 non-null    float64
 26  PH-BA   293 non-null    float64
dtypes: float64(6), int64(19), object(2)
memory usage: 61.9+ KB

In [14]:
# 전년도 성적을 가지고 다음해 연봉이 정해지기 때문에
# 연도는 연봉 기준으로 정리한다.
# 2020 데이터면 2019년의 stats과 2020년의 salary로 보면 됨

stats_2019['연도'] = 2020
stats_2020['연도'] = 2021
stats_2021['연도'] = 2022
stats_2022['연도'] = 2023
stats_2023['연도'] = 2024

In [15]:
stats_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      293 non-null    int64
 1   선수명     293 non-null    object
 2   팀명      293 non-null    object
 3   AVG     271 non-null    float64
 4   G       293 non-null    int64
 5   PA      293 non-null    int64
 6   AB      293 non-null    int64
 7   R       293 non-null    int64
 8   H       293 non-null    int64
 9   2B      293 non-null    int64
 10  3B      293 non-null    int64
 11  HR      293 non-null    int64
 12  TB      293 non-null    int64
 13  RBI     293 non-null    int64
 14  SAC     293 non-null    int64
 15  SF      293 non-null    int64
 16  BB      293 non-null    int64
 17  IBB     293 non-null    int64
 18  HBP     293 non-null    int64
 19  SO      293 non-null    int64
 20  GDP     293 non-null    int64
 21  SLG     271 non-null    float64
 22  OBP     271 non-null    float64
 23  OPS     271 non-null    float64
 24  MH      293 non-null    int64
 25  RISP    293 non-null    float64
 26  PH-BA   293 non-null    float64
 27  연도      293 non-null    int64
dtypes: float64(6), int64(20), object(2)
memory usage: 64.2+ KB

In [29]:
df2020 = pd.merge(left=stats_2019, right=salary, how='left',on=['선수명','팀명','연도'],sort=False)
df2021 = pd.merge(left=stats_2020, right=salary, how='left',on=['선수명','팀명','연도'],sort=False)
df2022 = pd.merge(left=stats_2021, right=salary, how='left',on=['선수명','팀명','연도'],sort=False)
df2023 = pd.merge(left=stats_2022, right=salary, how='left',on=['선수명','팀명','연도'],sort=False)
df2024 = pd.merge(left=stats_2023, right=salary, how='left',on=['선수명','팀명','연도'],sort=False)

In [34]:
df2020.loc[df2020['선수명'] == '김민수']

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
207,16,김민수,롯데,0.235,11,37,34,0,8,3,...,2,0.324,0.297,0.621,1,0.333,0.0,2020,"3,000",0.15
227,21,김민수,삼성,0.205,29,41,39,5,8,1,...,0,0.231,0.220,0.451,1,0.100,0.5,2020,"4,300",-0.04

In [35]:
stats_2019[stats_2019['선수명'] == '김민수']

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도
206,16,김민수,롯데,0.235,11,37,34,0,8,3,...,2,14,2,0.324,0.297,0.621,1,0.333,0.0,2020
226,21,김민수,삼성,0.205,29,41,39,5,8,1,...,0,16,0,0.231,0.220,0.451,1,0.100,0.5,2020

In [36]:
stats_2020[stats_2020['선수명'] == '김민수']

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도
55,20,김민수,KT,NaN,1,0,0,0,0,0,...,0,0,0,NaN,NaN,NaN,0,0.000,0.0,2021
202,13,김민수,롯데,0.250,3,10,8,1,2,0,...,0,4,0,0.250,0.40,0.650,1,0.333,0.0,2021
233,24,김민수,삼성,0.174,17,26,23,3,4,0,...,0,6,0,0.174,0.24,0.414,0,0.143,0.0,2021

In [41]:
hitter_salary_stats = pd.concat([df2020,df2021,df2022,df2023,df2024], ignore_index=True)

In [42]:
hitter_salary_stats.shape

(1495, 30)

In [43]:
hitter_salary_stats

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
0,4,최형우,KIA,0.300,136,555,456,65,137,31,...,13,0.485,0.413,0.898,38,0.263,0.000,2020,"150,000",6.59
1,11,이창진,KIA,0.270,133,470,400,57,108,25,...,8,0.383,0.363,0.746,27,0.267,0.333,2020,"8,500",0.27
2,12,박찬호,KIA,0.260,133,541,504,60,131,15,...,8,0.317,0.300,0.617,36,0.308,0.000,2020,"10,500",-0.77
3,7,김선빈,KIA,0.292,121,447,394,55,115,22,...,7,0.371,0.360,0.731,32,0.297,0.500,2020,"45,000",2.43
4,1,안치홍,KIA,0.315,105,408,362,45,114,18,...,9,0.412,0.380,0.792,32,0.234,0.200,2020,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,27,박상원,한화,NaN,3,0,0,0,0,0,...,0,NaN,NaN,NaN,0,0.000,0.000,2024,"19,500",0.56
1491,1,이재용,한화,0.500,2,2,2,1,1,0,...,0,0.500,0.500,1.000,0,0.000,0.000,2024,"3,100",0.00
1492,27,강재민,한화,NaN,1,0,0,0,0,0,...,0,NaN,NaN,NaN,0,0.000,0.000,2024,"14,500",0.00
1493,27,김서현,한화,NaN,1,0,0,0,0,0,...,0,NaN,NaN,NaN,0,0.000,0.000,2024,"3,300",0.87
1494,27,박준영,한화,NaN,1,0,0,0,0,0,...,0,NaN,NaN,NaN,0,0.000,0.000,2024,NaN,NaN

In [44]:
hitter_salary_stats.to_csv('hitter_salary_stats.csv',index=False)

In [27]:
df2020.shape

(294, 30)

In [28]:
df2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      294 non-null    int64
 1   선수명     294 non-null    object
 2   팀명      294 non-null    object
 3   AVG     272 non-null    float64
 4   G       294 non-null    int64
 5   PA      294 non-null    int64
 6   AB      294 non-null    int64
 7   R       294 non-null    int64
 8   H       294 non-null    int64
 9   2B      294 non-null    int64
 10  3B      294 non-null    int64
 11  HR      294 non-null    int64
 12  TB      294 non-null    int64
 13  RBI     294 non-null    int64
 14  SAC     294 non-null    int64
 15  SF      294 non-null    int64
 16  BB      294 non-null    int64
 17  IBB     294 non-null    int64
 18  HBP     294 non-null    int64
 19  SO      294 non-null    int64
 20  GDP     294 non-null    int64
 21  SLG     272 non-null    float64
 22  OBP     272 non-null    float64
 23  OPS     272 non-null    float64
 24  MH      294 non-null    int64
 25  RISP    294 non-null    float64
 26  PH-BA   294 non-null    float64
 27  연도      294 non-null    int64
 28  연봉(만원)  214 non-null    object
 29  WAR     214 non-null    float64
dtypes: float64(7), int64(20), object(3)
memory usage: 69.0+ KB

In [ ]:
df_hitter['연봉(만원)']  = df_hitter['연봉(만원)'].str.replace(',','').astype('int64')

In [ ]:
df_hitter = df_hitter.drop(['팀'], axis=1)

In [ ]:
df_hitter['이전연봉'] = 0

In [ ]:
df_hitter.shape

(1401, 32)

겹치는 선수명의 해당하는 연도의 작년 연봉을 이전연봉 컬럼에 넣어주는 것

In [ ]:
df_2021 = df_hitter.loc[df_hitter['연도'] == 2021][['선수명','연봉(만원)','이전연봉','연도','팀명']]
df_2020 = df_hitter.loc[df_hitter['연도'] == 2020][['선수명', '연봉(만원)','연도']]

In [ ]:
df_2020

     선수명  연봉(만원)    연도
0    최형우  150000  2020
1    김동한    4500  2020
2    김준태    3800  2020
3    김문호    5000  2020
4    한동희    4700  2020
..   ...     ...   ...
258  노진혁   14000  2020
259  박석민   70000  2020
260  김성욱   12000  2020
261  권희동   13500  2020
262  강진성    3800  2020

[263 rows x 3 columns]

In [ ]:
df_2021

     선수명  연봉(만원)  이전연봉    연도  팀명
263  김민수    4700     0  2021  롯데
264  김민수    3200     0  2021  롯데
265  김민수    3000     0  2021  롯데
266  김민수    7000     0  2021  롯데
267  김민수    4700     0  2021  삼성
..   ...     ...   ...   ...  ..
550  박민우   63000     0  2021  NC
551  강진성   12000     0  2021  NC
552  권희동   17000     0  2021  NC
553  박석민   70000     0  2021  NC
554  이상호    9000     0  2021  NC

[292 rows x 5 columns]

In [ ]:
df_hitter = df_hitter['연봉(만원)'].loc[df_hitter['연도'] == 2020]

0      150000
1        4500
2        3800
3        5000
4        4700
        ...
258     14000
259     70000
260     12000
261     13500
262      3800
Name: 연봉(만원), Length: 263, dtype: int64

In [ ]:
df_hitter['이전'] = df_hitter['연봉(만원)'].loc[df_hitter['연도'] == 2020]

In [ ]:
df_hitter.loc[df_hitter['선수명'] == '김민수'][['연봉(만원)','팀명','팀','선수명','연도','AVG']]

      연봉(만원)  팀명    팀  선수명    연도    AVG
24     2,700  롯데  KIA  김민수  2020  0.235
25     4,300  롯데   삼성  김민수  2020  0.235
26     3,000  롯데   롯데  김민수  2020  0.235
27     6,500  롯데   KT  김민수  2020  0.235
28     2,700  삼성  KIA  김민수  2020  0.205
29     4,300  삼성   삼성  김민수  2020  0.205
30     3,000  삼성   롯데  김민수  2020  0.205
31     6,500  삼성   KT  김민수  2020  0.205
263    4,700  롯데   삼성  김민수  2021  0.250
264    3,200  롯데   롯데  김민수  2021  0.250
265    3,000  롯데   NC  김민수  2021  0.250
266    7,000  롯데   KT  김민수  2021  0.250
267    4,700  삼성   삼성  김민수  2021  0.174
268    3,200  삼성   롯데  김민수  2021  0.174
269    3,000  삼성   NC  김민수  2021  0.174
270    7,000  삼성   KT  김민수  2021  0.174
271    4,700  KT   삼성  김민수  2021    NaN
272    3,200  KT   롯데  김민수  2021    NaN
273    3,000  KT   NC  김민수  2021    NaN
274    7,000  KT   KT  김민수  2021    NaN
592    3,000  롯데  KIA  김민수  2022  0.241
593    6,200  롯데   삼성  김민수  2022  0.241
594    5,300  롯데   롯데  김민수  2022  0.241
595    3,000  롯데   롯데  김민수  2022  0.241
596   11,500  롯데   KT  김민수  2022  0.241
597    3,000  롯데   키움  김민수  2022  0.241
598    3,000  삼성  KIA  김민수  2022  0.263
599    6,200  삼성   삼성  김민수  2022  0.263
600    5,300  삼성   롯데  김민수  2022  0.263
601    3,000  삼성   롯데  김민수  2022  0.263
602   11,500  삼성   KT  김민수  2022  0.263
603    3,000  삼성   키움  김민수  2022  0.263
604    3,000  KT  KIA  김민수  2022    NaN
605    6,200  KT   삼성  김민수  2022    NaN
606    5,300  KT   롯데  김민수  2022    NaN
607    3,000  KT   롯데  김민수  2022    NaN
608   11,500  KT   KT  김민수  2022    NaN
609    3,000  KT   키움  김민수  2022    NaN
846    3,000  롯데  KIA  김민수  2023  0.143
847    5,200  롯데   삼성  김민수  2023  0.143
848    6,300  롯데   롯데  김민수  2023  0.143
849   25,000  롯데   KT  김민수  2023  0.143
850    3,000  롯데  KIA  김민수  2023  0.257
851    5,200  롯데   삼성  김민수  2023  0.257
852    6,300  롯데   롯데  김민수  2023  0.257
853   25,000  롯데   KT  김민수  2023  0.257
1124   3,000  롯데  KIA  김민수  2024  0.209
1125   4,600  롯데   삼성  김민수  2024  0.209
1126   6,000  롯데   LG  김민수  2024  0.209
1127  16,000  롯데   KT  김민수  2024  0.209

In [ ]:
df_hitter['이전'] = df_hitter['연봉(만원)'].loc[df_hitter['연도'] == 2020]
df_hitter['2022'] = df_hitter['연봉(만원)'].loc[df_hitter['연도'] == 2020]
df_hitter['2021'] = df_hitter['연봉(만원)'].loc[df_hitter['연도'] == 2020]

In [ ]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4205 entries, 0 to 4204
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수      4205 non-null   object
 1   연도      4205 non-null   int64
 2   팀       4205 non-null   object
 3   연봉(만원)  4205 non-null   object
 4   WAR     4205 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 164.4+ KB

In [ ]:
salary.loc[salary['선수'] == '김민수']

       선수    연도    팀  연봉(만원)   WAR
79    김민수  2020  KIA   2,700  0.00
118   김민수  2020   삼성   4,300 -0.04
455   김민수  2020   롯데   3,000  0.15
693   김민수  2020   KT   6,500 -0.22
968   김민수  2021   삼성   4,700  0.24
1301  김민수  2021   롯데   3,200  0.32
1482  김민수  2021   NC   3,000 -0.13
1524  김민수  2021   KT   7,000  0.89
1748  김민수  2022  KIA   3,000  0.00
1778  김민수  2022   삼성   6,200  0.00
2116  김민수  2022   롯데   5,300  0.33
2159  김민수  2022   롯데   3,000 -0.07
2360  김민수  2022   KT  11,500  2.53
2478  김민수  2022   키움   3,000  0.00
2571  김민수  2023  KIA   3,000  0.00
2621  김민수  2023   삼성   5,200 -0.03
2954  김민수  2023   롯데   6,300 -0.23
3211  김민수  2023   KT  25,000 -0.18
3449  김민수  2024  KIA   3,000  0.00
3505  김민수  2024   삼성   4,600  0.10
3752  김민수  2024   LG   6,000 -0.21
4050  김민수  2024   KT  16,000  0.66

In [ ]:
df_min = df_hitter.loc[df_hitter['G'] > 79]

In [ ]:
df = df_min.drop(['순위','선수명','팀명','연도'],axis=1)
target = df_min['연봉(만원)']

In [ ]:
df_min.head()

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
0,4,최형우,KIA,0.300,136,555,456,65,137,31,...,13,0.485,0.413,0.898,38,0.263,0.000,2020,150000,6.59
8,17,정훈,롯데,0.226,88,222,190,26,43,4,...,4,0.289,0.324,0.613,12,0.176,0.050,2020,6400,2.29
9,1,민병헌,롯데,0.304,101,420,369,52,112,24,...,9,0.453,0.379,0.832,32,0.289,0.333,2020,125000,-1.35
11,26,나균안,롯데,0.124,104,209,185,12,23,4,...,5,0.195,0.188,0.383,4,0.098,0.000,2020,4300,0.00
14,12,이원석,삼성,0.246,111,455,395,44,97,20,...,10,0.441,0.327,0.768,24,0.304,0.000,2020,30000,0.14

# 3.2 데이터 스케일링 - 표준화

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)