# 1. Library Import

In [281]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [282]:
%matplotlib inline

import matplotlib as mpl  # 기본 설정
import matplotlib.pyplot as plt  # 그래프 그리기
import matplotlib.font_manager as fm  # 폰트 관리


!apt-get update -qq         # apt-get 패키지 설치 명령어, -qq : 에러외 메세지 숨기기
!apt-get install fonts-nanum* -qq #나눔글꼴 설치

fe = fm.FontEntry(fname=r'/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic') #파일 저장되어있는 경로와 이름 설정
fm.fontManager.ttflist.insert(0, fe)  # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 10, 'font.family': 'NanumGothic'}) #폰트설정

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

# 2. 데이터 불러오기 및 확인

In [283]:
salary = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/Salary_WAR.csv')
for i in range(19,24):
  globals()['stats_20' + str(i)] = pd.read_csv(f'/content/drive/MyDrive/Colab Notebooks/HK/kbo_salary/KBO_Salary/kbo_player_stats_full20{i}.csv')

In [284]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4205 entries, 0 to 4204
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수      4205 non-null   object
 1   연도      4205 non-null   int64
 2   팀       4205 non-null   object
 3   연봉(만원)  4205 non-null   object
 4   WAR     4205 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 164.4+ KB

In [285]:
print(f'2020년 stats 데이터 Shape : {stats_2020.shape}')
print(f'2021년 stats 데이터 Shape : {stats_2020.shape}')
print(f'2022년 stats 데이터 Shape : {stats_2020.shape}')
print(f'2023년 stats 데이터 Shape : {stats_2020.shape}')

2020년 stats 데이터 Shape : (300, 27)
2021년 stats 데이터 Shape : (300, 27)
2022년 stats 데이터 Shape : (300, 27)
2023년 stats 데이터 Shape : (300, 27)

In [286]:
stats_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      293 non-null    int64
 1   선수명     293 non-null    object
 2   팀명      293 non-null    object
 3   AVG     271 non-null    float64
 4   G       293 non-null    int64
 5   PA      293 non-null    int64
 6   AB      293 non-null    int64
 7   R       293 non-null    int64
 8   H       293 non-null    int64
 9   2B      293 non-null    int64
 10  3B      293 non-null    int64
 11  HR      293 non-null    int64
 12  TB      293 non-null    int64
 13  RBI     293 non-null    int64
 14  SAC     293 non-null    int64
 15  SF      293 non-null    int64
 16  BB      293 non-null    int64
 17  IBB     293 non-null    int64
 18  HBP     293 non-null    int64
 19  SO      293 non-null    int64
 20  GDP     293 non-null    int64
 21  SLG     271 non-null    float64
 22  OBP     271 non-null    float64
 23  OPS     271 non-null    float64
 24  MH      293 non-null    int64
 25  RISP    293 non-null    float64
 26  PH-BA   293 non-null    float64
dtypes: float64(6), int64(19), object(2)
memory usage: 61.9+ KB

In [287]:
salary['연도'].unique()

array([2020, 2021, 2022, 2023, 2024])

In [288]:
stats_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      300 non-null    int64
 1   선수명     300 non-null    object
 2   팀명      300 non-null    object
 3   AVG     265 non-null    float64
 4   G       300 non-null    int64
 5   PA      300 non-null    int64
 6   AB      300 non-null    int64
 7   R       300 non-null    int64
 8   H       300 non-null    int64
 9   2B      300 non-null    int64
 10  3B      300 non-null    int64
 11  HR      300 non-null    int64
 12  TB      300 non-null    int64
 13  RBI     300 non-null    int64
 14  SAC     300 non-null    int64
 15  SF      300 non-null    int64
 16  BB      300 non-null    int64
 17  IBB     300 non-null    int64
 18  HBP     300 non-null    int64
 19  SO      300 non-null    int64
 20  GDP     300 non-null    int64
 21  SLG     265 non-null    float64
 22  OBP     265 non-null    float64
 23  OPS     265 non-null    float64
 24  MH      300 non-null    int64
 25  RISP    300 non-null    float64
 26  PH-BA   300 non-null    float64
dtypes: float64(6), int64(19), object(2)
memory usage: 63.4+ KB

# 3. 데이터 전처리  
## 3.1. 컬럼명 일치 및 데이터 타입변경

In [289]:
salary.rename(columns={'선수':'선수명'},inplace=True)

In [290]:
salary.rename(columns={'팀':'팀명'},inplace=True)

In [291]:
# 연봉 데이터타입 int로 변경
salary['연봉(만원)']  = salary['연봉(만원)'].str.replace(',','').astype('int64')

In [292]:
# 전년도 성적을 가지고 다음해 연봉이 정해지기 때문에
# 연도는 연봉 기준으로 정리한다.
# 2020 데이터면 2019년의 stats과 2020년의 salary로 보면 됨


# 우선 현재 연도로 확인한다.

stats_2019['연도'] = 2019
stats_2020['연도'] = 2020
stats_2021['연도'] = 2021
stats_2022['연도'] = 2022
stats_2023['연도'] = 2023

### 3.1.2 팀명 SK --> SSG

In [293]:
stats_2019['팀명'].loc[stats_2019['팀명'] == 'SK'] = 'SSG'
stats_2020['팀명'].loc[stats_2020['팀명'] == 'SK'] = 'SSG'
stats_2021['팀명'].loc[stats_2021['팀명'] == 'SK'] = 'SSG'
stats_2022['팀명'].loc[stats_2022['팀명'] == 'SK'] = 'SSG'
stats_2023['팀명'].loc[stats_2023['팀명'] == 'SK'] = 'SSG'

<ipython-input-293-945cef1675ac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_2019['팀명'].loc[stats_2019['팀명'] == 'SK'] = 'SSG'
<ipython-input-293-945cef1675ac>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_2020['팀명'].loc[stats_2020['팀명'] == 'SK'] = 'SSG'
<ipython-input-293-945cef1675ac>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_2021['팀명'].loc[stats_2021['팀명'] == 'SK'] = 'SSG'
<ipython-input-293-945cef1675ac>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_2022['팀명'].loc[stats_2022['팀명'] == 'SK'] = 'SSG'
<ipython-input-293-945cef1675ac>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_2023['팀명'].loc[stats_2023['팀명'] == 'SK'] = 'SSG'

In [294]:
stats_2020['팀명'].unique()

array(['KIA', 'KT', 'LG', 'NC', 'SSG', '두산', '롯데', '삼성', '키움', '한화'],
      dtype=object)

In [295]:
salary['팀명'][salary['팀명'] == 'SK'] = 'SSG'

<ipython-input-295-447dd76e09da>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salary['팀명'][salary['팀명'] == 'SK'] = 'SSG'

## 3.2. Stat과 연봉 데이터 merge

### 3.2.1 동명이인 및 팀 이적 확인

In [296]:
salary[salary['연도'] == 2021]

      선수명    연도   팀명  연봉(만원)   WAR
841   브룩스  2021  KIA  100000  2.31
842   최형우  2021  KIA   90000  1.51
843    터커  2021  KIA   70000  0.35
844   김선빈  2021  KIA   45000  2.70
845    멩덴  2021  KIA   42500  3.48
...   ...   ...  ...     ...   ...
1663  김인범  2021   키움    3000  0.25
1664  문찬종  2021   키움    3000 -0.14
1665  박주홍  2021   키움    3000 -0.15
1666  김신회  2021   키움    3000  0.00
1667  박성우  2021   키움    2700  0.00

[827 rows x 5 columns]

In [297]:
salary[salary['연도'] == 2020]

     선수명    연도   팀명  연봉(만원)   WAR
0    양현종  2020  KIA  230000  4.87
1    최형우  2020  KIA  150000  6.59
2     가뇽  2020  KIA   65000  4.68
3    나지완  2020  KIA   60000  2.01
4     터커  2020  KIA   55000  3.46
..   ...   ...  ...     ...   ...
836  김신회  2020   키움    2700  0.00
837  박주성  2020   키움    2700  0.06
838  윤정현  2020   키움    2700 -0.52
839  조영건  2020   키움    2700  0.08
840  주성원  2020   키움    2700  0.00

[841 rows x 5 columns]

In [298]:
# 동명이인 확인

salary[(salary['연도'] == 2020) & (salary['선수명'] == '김성민')]

     선수명    연도   팀명  연봉(만원)   WAR
218  김성민  2020   두산    2700  0.00
300  김성민  2020  SSG    2700  0.04
326  김성민  2020  SSG    2700  0.00
780  김성민  2020   키움    9700 -0.21

In [299]:
# stats Data에 있는 Na값 drop
# NA 값이 있는 이유는 경기를 많이 뛰지 않아 성적에 기록이 남지 않았기 때문이다
# 후에 다시 규정타석수를 통해 전처리를 진행할 예정

stats_2020.dropna(inplace=True)
stats_2021.dropna(inplace=True)
stats_2022.dropna(inplace=True)
stats_2023.dropna(inplace=True)

In [300]:
stats_2020.shape

(265, 28)

In [301]:
# df2020 = pd.merge(left=stats_2019, right=salary[salary['연도'] == 2020], how='left',on=['선수명','팀명'],sort=False)
df2020 = pd.merge(left=stats_2020, right=salary[salary['연도'] == 2020], how='left',on=['선수명','팀명','연도'],sort=False)
df2021 = pd.merge(left=stats_2021, right=salary[salary['연도'] == 2021], how='left',on=['선수명','팀명','연도'],sort=False)
df2022 = pd.merge(left=stats_2022, right=salary[salary['연도'] == 2022], how='left',on=['선수명','팀명','연도'],sort=False)
df2023 = pd.merge(left=stats_2023, right=salary[salary['연도'] == 2023], how='left',on=['선수명','팀명','연도'],sort=False)

In [302]:
stats_2022[stats_2022['선수명'] == '김민수']

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도
190,8,김민수,롯데,0.257,57,156,140,9,36,6,...,4,48,2,0.300,0.320,0.620,7,0.333,0.5,2022
200,23,김민수,롯데,0.143,5,7,7,0,1,0,...,0,4,0,0.143,0.143,0.286,0,0.333,0.0,2022

In [303]:
df2020.shape

(266, 30)

In [304]:
df2020.loc[df2020.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
179,13,김민수,롯데,0.250,3,10,8,1,2,0,...,0,0.250,0.400,0.650,1,0.333,0.000,2020,3000.0,0.15
204,24,김민수,삼성,0.174,17,26,23,3,4,0,...,0,0.174,0.240,0.414,0,0.143,0.000,2020,4300.0,-0.04
125,1,김성민,SSG,0.286,9,16,14,4,4,0,...,0,0.714,0.375,1.089,1,0.200,0.000,2020,2700.0,0.04
126,1,김성민,SSG,0.286,9,16,14,4,4,0,...,0,0.714,0.375,1.089,1,0.200,0.000,2020,2700.0,0.00
128,26,김재현,SSG,0.143,8,14,14,3,2,0,...,0,0.143,0.143,0.286,0,0.000,0.000,2020,5000.0,-0.16
200,25,김재현,삼성,0.143,35,18,14,4,2,0,...,1,0.143,0.294,0.437,0,0.222,0.500,2020,5500.0,-0.13
233,25,김재현,키움,0.000,4,3,3,0,0,0,...,0,0.000,0.000,0.000,0,0.000,0.000,2020,7000.0,-0.10
72,24,이재원,LG,0.050,16,22,20,1,1,0,...,0,0.050,0.136,0.186,0,0.000,0.000,2020,2700.0,-0.46
108,23,이재원,SSG,0.185,80,251,222,18,41,8,...,12,0.248,0.266,0.514,7,0.237,0.333,2020,130000.0,0.11

In [305]:
# 2020년 stats과 연봉에 맞도록 들어가게 적절하지 않은 데이터 제거
# 이 경우 stats에는 없고 연봉 데이터에는 2명이 존재

# df2020 = df2020.drop(index=126)

In [306]:
df2021.loc[df2021.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
169,14,김민수,롯데,0.241,82,224,199,19,48,11,...,4,0.352,0.312,0.664,14,0.241,0.091,2021,3200.0,0.32
200,10,김민수,삼성,0.263,47,87,76,9,20,5,...,2,0.447,0.318,0.765,5,0.217,0.000,2021,4700.0,0.24
41,3,김민혁,KT,0.320,75,199,172,22,55,6,...,3,0.395,0.397,0.792,13,0.220,0.381,2021,6500.0,1.35
157,23,김민혁,두산,0.000,6,8,6,0,0,0,...,0,0.000,0.250,0.250,0,0.000,0.000,2021,3400.0,-0.07
98,3,이명기,NC,0.293,56,232,191,30,56,12,...,2,0.387,0.410,0.797,18,0.300,0.250,2021,27000.0,0.76
238,20,이명기,키움,0.167,3,8,6,0,1,0,...,0,0.167,0.375,0.542,0,0.000,0.000,2021,3000.0,0.06
189,16,이원석,삼성,0.231,131,480,399,40,92,19,...,11,0.346,0.341,0.687,18,0.309,0.250,2021,30000.0,1.01
255,21,이원석,한화,0.175,43,130,114,12,20,1,...,1,0.228,0.238,0.466,2,0.217,0.667,2021,3000.0,-1.05
70,9,이재원,LG,0.247,62,171,154,22,38,6,...,2,0.383,0.316,0.699,9,0.191,0.000,2021,3200.0,0.75
120,4,이재원,SSG,0.280,107,313,271,29,76,13,...,14,0.362,0.358,0.720,16,0.292,0.250,2021,130000.0,1.38
80,26,이주형,LG,0.125,14,19,16,3,2,0,...,0,0.125,0.222,0.347,0,0.000,0.000,2021,3000.0,0.07
237,28,이주형,키움,0.100,5,11,10,1,1,0,...,0,0.400,0.182,0.582,0,0.250,0.000,2021,3000.0,0.01

In [307]:
df2022.loc[df2022.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
175,8,김민수,롯데,0.257,57,156,140,9,36,6,...,2,0.300,0.320,0.620,7,0.333,0.500,2022,5300.0,0.33
176,8,김민수,롯데,0.257,57,156,140,9,36,6,...,2,0.300,0.320,0.620,7,0.333,0.500,2022,3000.0,-0.07
186,23,김민수,롯데,0.143,5,7,7,0,1,0,...,0,0.143,0.143,0.286,0,0.333,0.000,2022,5300.0,0.33
187,23,김민수,롯데,0.143,5,7,7,0,1,0,...,0,0.143,0.143,0.286,0,0.333,0.000,2022,3000.0,-0.07
28,5,김민혁,KT,0.284,132,434,373,47,106,10,...,10,0.322,0.349,0.671,20,0.279,0.296,2022,9000.0,1.20
149,8,김민혁,두산,0.284,38,97,88,11,25,2,...,6,0.477,0.351,0.828,5,0.320,0.294,2022,3200.0,0.01
124,14,김재현,SSG,0.222,18,20,18,2,4,1,...,2,0.278,0.222,0.500,1,0.222,0.000,2022,4000.0,-0.30
232,14,김재현,키움,0.207,56,88,82,4,17,4,...,3,0.293,0.233,0.526,3,0.286,0.000,2022,6500.0,-0.70
84,9,이명기,NC,0.260,94,341,300,36,78,13,...,8,0.317,0.331,0.648,20,0.253,0.167,2022,17500.0,-0.38
245,7,이명기,키움,0.250,2,4,4,0,1,0,...,0,0.250,0.250,0.500,0,0.000,0.000,2022,3000.0,-0.07
199,12,이원석,삼성,0.267,88,335,288,31,77,13,...,7,0.417,0.346,0.763,18,0.368,0.500,2022,30000.0,1.69
265,25,이원석,한화,0.114,20,39,35,4,4,0,...,1,0.200,0.184,0.384,0,0.000,0.000,2022,3300.0,-0.46
61,14,이재원,LG,0.224,85,253,223,31,50,8,...,3,0.453,0.316,0.769,10,0.262,0.286,2022,5200.0,1.62
111,21,이재원,SSG,0.201,105,279,234,27,47,6,...,13,0.278,0.296,0.574,5,0.208,0.125,2022,100000.0,0.23

In [309]:
df2023.loc[df2023.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,GDP,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR
30,1,김민혁,KT,0.297,113,448,397,68,118,20,...,4,0.385,0.356,0.741,33,0.284,0.286,2023,15000,3.85
157,26,김민혁,두산,0.138,21,36,29,2,4,1,...,3,0.172,0.250,0.422,0,0.125,0.111,2023,4500,-0.14
215,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,1,0.143,0.095,0.238,1,0.250,0.000,2023,18000,-0.62
216,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,1,0.143,0.095,0.238,1,0.250,0.000,2023,4300,-0.43
227,14,이원석,키움,0.246,89,345,305,22,75,10,...,9,0.298,0.326,0.624,18,0.286,0.167,2023,20000,-0.99
264,18,이원석,한화,0.190,81,138,116,20,22,1,...,3,0.216,0.319,0.535,3,0.212,0.000,2023,3300,0.25
66,14,이재원,LG,0.214,57,129,112,15,24,5,...,1,0.366,0.295,0.661,4,0.242,0.133,2023,8500,0.15
127,24,이재원,SSG,0.091,27,48,44,3,4,1,...,4,0.114,0.128,0.242,0,0.100,1.000,2023,10000,-0.81
234,5,이주형,키움,0.326,69,243,215,32,70,13,...,4,0.507,0.390,0.897,20,0.339,0.167,2023,3700,0.00
235,5,이주형,키움,0.326,69,243,215,32,70,13,...,4,0.507,0.390,0.897,20,0.339,0.167,2023,3300,2.55

In [228]:
# 중복으로 들어간 데이터를 선수 정보와 연봉에 맞게 들어가도록 특정 데이터 drop
# df2023 = df2023.drop(index=[216,234])

## 4.2. 후년 연봉 컬럼 추가

In [310]:
salary['후년연봉'] = salary['연봉(만원)']

In [230]:
salary['연도'].unique()

array([2020, 2021, 2022, 2023, 2024])

In [231]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4205 entries, 0 to 4204
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수명     4205 non-null   object
 1   연도      4205 non-null   int64
 2   팀명      4205 non-null   object
 3   연봉(만원)  4205 non-null   int64
 4   WAR     4205 non-null   float64
 5   후년연봉    4205 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 197.2+ KB

In [232]:
salary

      선수명    연도   팀명  연봉(만원)   WAR    후년연봉
0     양현종  2020  KIA  230000  4.87  230000
1     최형우  2020  KIA  150000  6.59  150000
2      가뇽  2020  KIA   65000  4.68   65000
3     나지완  2020  KIA   60000  2.01   60000
4      터커  2020  KIA   55000  3.46   55000
...   ...   ...  ...     ...   ...     ...
4200  박성빈  2024   키움    3000 -0.07    3000
4201  우승원  2024   키움    3000  0.00    3000
4202  박윤성  2024   키움    3000 -0.03    3000
4203  원성준  2024   키움    1500 -0.22    1500
4204  신효수  2024   키움    1500  0.00    1500

[4205 rows x 6 columns]

In [311]:
sal = salary[['선수명','팀명','연도','후년연봉']]
sal['연도'] = (sal['연도'] - 1)

<ipython-input-311-38a4e1c30a90>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sal['연도'] = (sal['연도'] - 1)

In [312]:
sal.loc[sal['연도'] == 2020]

      선수명   팀명    연도    후년연봉
841   브룩스  KIA  2020  100000
842   최형우  KIA  2020   90000
843    터커  KIA  2020   70000
844   김선빈  KIA  2020   45000
845    멩덴  KIA  2020   42500
...   ...  ...   ...     ...
1663  김인범   키움  2020    3000
1664  문찬종   키움  2020    3000
1665  박주홍   키움  2020    3000
1666  김신회   키움  2020    3000
1667  박성우   키움  2020    2700

[827 rows x 4 columns]

In [313]:
all2020 = pd.merge(left=df2020, right=sal.loc[sal['연도'] == 2020], how='left',on=['선수명','팀명','연도' ],sort=False)
all2021 = pd.merge(left=df2021, right=sal.loc[sal['연도'] == 2021], how='left',on=['선수명','팀명','연도'],sort=False)
all2022 = pd.merge(left=df2022, right=sal.loc[sal['연도'] == 2022], how='left',on=['선수명','팀명','연도'],sort=False)
all2023 = pd.merge(left=df2023, right=sal.loc[sal['연도'] == 2023], how='left',on=['선수명','팀명','연도'],sort=False)

In [314]:
all2020

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
0,7,터커,KIA,0.306,142,631,542,100,166,40,...,0.557,0.398,0.955,44,0.300,0.000,2020,55000.0,3.46,70000.0
1,21,박찬호,KIA,0.223,141,531,480,63,107,16,...,0.275,0.276,0.551,30,0.185,0.000,2020,10500.0,-0.77,10000.0
2,2,최형우,KIA,0.354,140,600,522,93,185,37,...,0.590,0.433,1.023,55,0.374,1.000,2020,150000.0,6.59,90000.0
3,8,나지완,KIA,0.291,137,556,468,73,136,19,...,0.444,0.392,0.836,32,0.338,0.250,2020,60000.0,2.01,40000.0
4,13,유민상,KIA,0.246,126,456,391,38,96,23,...,0.366,0.341,0.707,15,0.308,0.273,2020,6000.0,-0.25,10500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,27,이도윤,한화,0.208,14,25,24,3,5,1,...,0.250,0.240,0.490,0,0.200,0.000,2020,3000.0,-0.09,3200.0
262,20,양성우,한화,0.222,5,9,9,1,2,0,...,0.222,0.222,0.444,0,0.000,0.000,2020,7000.0,-0.13,NaN
263,2,김건,한화,0.400,4,5,5,2,2,0,...,0.400,0.400,0.800,0,1.000,0.000,2020,NaN,NaN,NaN
264,3,최승준,한화,0.333,2,4,3,1,1,0,...,0.333,0.500,0.833,0,0.500,0.000,2020,4000.0,-0.04,NaN
265,1,허관회,한화,0.500,1,2,2,0,1,0,...,0.500,0.500,1.000,0,0.000,0.000,2020,2700.0,0.02,3100.0

In [315]:
all2020.loc[all2020.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
179,13,김민수,롯데,0.250,3,10,8,1,2,0,...,0.250,0.400,0.650,1,0.333,0.000,2020,3000.0,0.15,3200.0
204,24,김민수,삼성,0.174,17,26,23,3,4,0,...,0.174,0.240,0.414,0,0.143,0.000,2020,4300.0,-0.04,4700.0
125,1,김성민,SSG,0.286,9,16,14,4,4,0,...,0.714,0.375,1.089,1,0.200,0.000,2020,2700.0,0.04,3000.0
126,1,김성민,SSG,0.286,9,16,14,4,4,0,...,0.714,0.375,1.089,1,0.200,0.000,2020,2700.0,0.00,3000.0
128,26,김재현,SSG,0.143,8,14,14,3,2,0,...,0.143,0.143,0.286,0,0.000,0.000,2020,5000.0,-0.16,NaN
200,25,김재현,삼성,0.143,35,18,14,4,2,0,...,0.143,0.294,0.437,0,0.222,0.500,2020,5500.0,-0.13,5000.0
233,25,김재현,키움,0.000,4,3,3,0,0,0,...,0.000,0.000,0.000,0,0.000,0.000,2020,7000.0,-0.10,7000.0
72,24,이재원,LG,0.050,16,22,20,1,1,0,...,0.050,0.136,0.186,0,0.000,0.000,2020,2700.0,-0.46,3200.0
108,23,이재원,SSG,0.185,80,251,222,18,41,8,...,0.248,0.266,0.514,7,0.237,0.333,2020,130000.0,0.11,130000.0

In [320]:
# 2020년 stats과 연봉에 맞도록 들어가게 적절하지 않은 데이터 제거
# 이 경우 stats에는 없고 연봉 데이터에는 2명이 존재

all2020 = all2020.drop(index=126)

In [321]:
all2020.shape

(265, 31)

In [322]:
all2021.loc[all2021.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
169,14,김민수,롯데,0.241,82,224,199,19,48,11,...,0.352,0.312,0.664,14,0.241,0.091,2021,3200.0,0.32,5300.0
170,14,김민수,롯데,0.241,82,224,199,19,48,11,...,0.352,0.312,0.664,14,0.241,0.091,2021,3200.0,0.32,3000.0
201,10,김민수,삼성,0.263,47,87,76,9,20,5,...,0.447,0.318,0.765,5,0.217,0.000,2021,4700.0,0.24,6200.0
41,3,김민혁,KT,0.320,75,199,172,22,55,6,...,0.395,0.397,0.792,13,0.220,0.381,2021,6500.0,1.35,9000.0
157,23,김민혁,두산,0.000,6,8,6,0,0,0,...,0.000,0.250,0.250,0,0.000,0.000,2021,3400.0,-0.07,3200.0
98,3,이명기,NC,0.293,56,232,191,30,56,12,...,0.387,0.410,0.797,18,0.300,0.250,2021,27000.0,0.76,17500.0
239,20,이명기,키움,0.167,3,8,6,0,1,0,...,0.167,0.375,0.542,0,0.000,0.000,2021,3000.0,0.06,3000.0
190,16,이원석,삼성,0.231,131,480,399,40,92,19,...,0.346,0.341,0.687,18,0.309,0.250,2021,30000.0,1.01,30000.0
256,21,이원석,한화,0.175,43,130,114,12,20,1,...,0.228,0.238,0.466,2,0.217,0.667,2021,3000.0,-1.05,3300.0
70,9,이재원,LG,0.247,62,171,154,22,38,6,...,0.383,0.316,0.699,9,0.191,0.000,2021,3200.0,0.75,5200.0
120,4,이재원,SSG,0.280,107,313,271,29,76,13,...,0.362,0.358,0.720,16,0.292,0.250,2021,130000.0,1.38,100000.0
80,26,이주형,LG,0.125,14,19,16,3,2,0,...,0.125,0.222,0.347,0,0.000,0.000,2021,3000.0,0.07,NaN
238,28,이주형,키움,0.100,5,11,10,1,1,0,...,0.400,0.182,0.582,0,0.250,0.000,2021,3000.0,0.01,3000.0

In [323]:
all2021 = all2021.drop(index=170)

In [324]:
salary.loc[salary['선수명']=='김민수']

      선수명    연도   팀명  연봉(만원)   WAR   후년연봉
79    김민수  2020  KIA    2700  0.00   2700
118   김민수  2020   삼성    4300 -0.04   4300
455   김민수  2020   롯데    3000  0.15   3000
693   김민수  2020   KT    6500 -0.22   6500
968   김민수  2021   삼성    4700  0.24   4700
1301  김민수  2021   롯데    3200  0.32   3200
1482  김민수  2021   NC    3000 -0.13   3000
1524  김민수  2021   KT    7000  0.89   7000
1748  김민수  2022  KIA    3000  0.00   3000
1778  김민수  2022   삼성    6200  0.00   6200
2116  김민수  2022   롯데    5300  0.33   5300
2159  김민수  2022   롯데    3000 -0.07   3000
2360  김민수  2022   KT   11500  2.53  11500
2478  김민수  2022   키움    3000  0.00   3000
2571  김민수  2023  KIA    3000  0.00   3000
2621  김민수  2023   삼성    5200 -0.03   5200
2954  김민수  2023   롯데    6300 -0.23   6300
3211  김민수  2023   KT   25000 -0.18  25000
3449  김민수  2024  KIA    3000  0.00   3000
3505  김민수  2024   삼성    4600  0.10   4600
3752  김민수  2024   LG    6000 -0.21   6000
4050  김민수  2024   KT   16000  0.66  16000

In [318]:
all2022.loc[all2022.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
175,8,김민수,롯데,0.257,57,156,140,9,36,6,...,0.300,0.320,0.620,7,0.333,0.500,2022,5300.0,0.33,6300.0
176,8,김민수,롯데,0.257,57,156,140,9,36,6,...,0.300,0.320,0.620,7,0.333,0.500,2022,3000.0,-0.07,6300.0
186,23,김민수,롯데,0.143,5,7,7,0,1,0,...,0.143,0.143,0.286,0,0.333,0.000,2022,5300.0,0.33,6300.0
187,23,김민수,롯데,0.143,5,7,7,0,1,0,...,0.143,0.143,0.286,0,0.333,0.000,2022,3000.0,-0.07,6300.0
28,5,김민혁,KT,0.284,132,434,373,47,106,10,...,0.322,0.349,0.671,20,0.279,0.296,2022,9000.0,1.20,15000.0
149,8,김민혁,두산,0.284,38,97,88,11,25,2,...,0.477,0.351,0.828,5,0.320,0.294,2022,3200.0,0.01,4500.0
124,14,김재현,SSG,0.222,18,20,18,2,4,1,...,0.278,0.222,0.500,1,0.222,0.000,2022,4000.0,-0.30,NaN
232,14,김재현,키움,0.207,56,88,82,4,17,4,...,0.293,0.233,0.526,3,0.286,0.000,2022,6500.0,-0.70,6500.0
84,9,이명기,NC,0.260,94,341,300,36,78,13,...,0.317,0.331,0.648,20,0.253,0.167,2022,17500.0,-0.38,NaN
246,7,이명기,키움,0.250,2,4,4,0,1,0,...,0.250,0.250,0.500,0,0.000,0.000,2022,3000.0,-0.07,NaN
199,12,이원석,삼성,0.267,88,335,288,31,77,13,...,0.417,0.346,0.763,18,0.368,0.500,2022,30000.0,1.69,NaN
266,25,이원석,한화,0.114,20,39,35,4,4,0,...,0.200,0.184,0.384,0,0.000,0.000,2022,3300.0,-0.46,3300.0
61,14,이재원,LG,0.224,85,253,223,31,50,8,...,0.453,0.316,0.769,10,0.262,0.286,2022,5200.0,1.62,8500.0
111,21,이재원,SSG,0.201,105,279,234,27,47,6,...,0.278,0.296,0.574,5,0.208,0.125,2022,100000.0,0.23,10000.0
238,21,이주형,키움,0.169,32,85,71,7,12,0,...,0.211,0.294,0.505,0,0.143,0.111,2022,3000.0,-0.17,3700.0
239,21,이주형,키움,0.169,32,85,71,7,12,0,...,0.211,0.294,0.505,0,0.143,0.111,2022,3000.0,-0.17,3300.0

In [325]:
# 중복으로 들어간 데이터를 선수 정보와 연봉에 맞게 들어가도록 특정 데이터 drop
all2022 = all2022.drop(index=[176,186,187])

In [319]:
all2023.loc[all2023.duplicated(['선수명'], keep=False)].sort_values('선수명')

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
30,1,김민혁,KT,0.297,113,448,397,68,118,20,...,0.385,0.356,0.741,33,0.284,0.286,2023,15000,3.85,24000.0
157,26,김민혁,두산,0.138,21,36,29,2,4,1,...,0.172,0.250,0.422,0,0.125,0.111,2023,4500,-0.14,3800.0
215,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,0.143,0.095,0.238,1,0.250,0.000,2023,18000,-0.62,17000.0
216,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,0.143,0.095,0.238,1,0.250,0.000,2023,18000,-0.62,4100.0
217,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,0.143,0.095,0.238,1,0.250,0.000,2023,4300,-0.43,17000.0
218,29,김태훈,삼성,0.095,11,22,21,0,2,1,...,0.143,0.095,0.238,1,0.250,0.000,2023,4300,-0.43,4100.0
229,14,이원석,키움,0.246,89,345,305,22,75,10,...,0.298,0.326,0.624,18,0.286,0.167,2023,20000,-0.99,40000.0
266,18,이원석,한화,0.190,81,138,116,20,22,1,...,0.216,0.319,0.535,3,0.212,0.000,2023,3300,0.25,3600.0
66,14,이재원,LG,0.214,57,129,112,15,24,5,...,0.366,0.295,0.661,4,0.242,0.133,2023,8500,0.15,7000.0
127,24,이재원,SSG,0.091,27,48,44,3,4,1,...,0.114,0.128,0.242,0,0.100,1.000,2023,10000,-0.81,NaN
236,5,이주형,키움,0.326,69,243,215,32,70,13,...,0.507,0.390,0.897,20,0.339,0.167,2023,3700,0.00,6600.0
237,5,이주형,키움,0.326,69,243,215,32,70,13,...,0.507,0.390,0.897,20,0.339,0.167,2023,3300,2.55,6600.0

In [326]:
# 중복으로 들어간 데이터를 선수 정보와 연봉에 맞게 들어가도록 특정 데이터 drop
all2022 = all2022.drop(index=[215,216,217])

In [237]:
salary.loc[salary['선수명'] == '박찬호']

      선수명    연도   팀명  연봉(만원)   WAR   후년연봉
12    박찬호  2020  KIA   10500 -0.77  10500
390   박찬호  2020   LG    2700  0.00   2700
853   박찬호  2021  KIA   10000  1.87  10000
1682  박찬호  2022  KIA   12000  4.10  12000
2519  박찬호  2023  KIA   20000  4.71  20000
3385  박찬호  2024  KIA   30000  2.60  30000

In [327]:
hitter_salary_stats = pd.concat([all2020, all2021,all2022,all2023], ignore_index=True)

In [328]:
hitter_salary_stats.loc[hitter_salary_stats['선수명'] == '김민수']

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
178,13,김민수,롯데,0.250,3,10,8,1,2,0,...,0.250,0.400,0.650,1,0.333,0.000,2020,3000.0,0.15,3200.0
203,24,김민수,삼성,0.174,17,26,23,3,4,0,...,0.174,0.240,0.414,0,0.143,0.000,2020,4300.0,-0.04,4700.0
434,14,김민수,롯데,0.241,82,224,199,19,48,11,...,0.352,0.312,0.664,14,0.241,0.091,2021,3200.0,0.32,5300.0
465,10,김민수,삼성,0.263,47,87,76,9,20,5,...,0.447,0.318,0.765,5,0.217,0.000,2021,4700.0,0.24,6200.0
709,8,김민수,롯데,0.257,57,156,140,9,36,6,...,0.300,0.320,0.620,7,0.333,0.500,2022,5300.0,0.33,6300.0
983,21,김민수,롯데,0.209,25,51,43,4,9,1,...,0.279,0.320,0.599,1,0.182,0.250,2023,6300.0,-0.23,NaN

In [329]:
hitter_salary_stats.reset_index(drop=True)

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
0,7,터커,KIA,0.306,142,631,542,100,166,40,...,0.557,0.398,0.955,44,0.300,0.000,2020,55000.0,3.46,70000.0
1,21,박찬호,KIA,0.223,141,531,480,63,107,16,...,0.275,0.276,0.551,30,0.185,0.000,2020,10500.0,-0.77,10000.0
2,2,최형우,KIA,0.354,140,600,522,93,185,37,...,0.590,0.433,1.023,55,0.374,1.000,2020,150000.0,6.59,90000.0
3,8,나지완,KIA,0.291,137,556,468,73,136,19,...,0.444,0.392,0.836,32,0.338,0.250,2020,60000.0,2.01,40000.0
4,13,유민상,KIA,0.246,126,456,391,38,96,23,...,0.366,0.341,0.707,15,0.308,0.273,2020,6000.0,-0.25,10500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,20,이명기,한화,0.175,14,42,40,2,7,1,...,0.200,0.214,0.414,2,0.200,0.000,2023,5000.0,-0.29,5000.0
1078,24,이성곤,한화,0.143,8,16,14,2,2,0,...,0.143,0.200,0.343,0,0.000,0.000,2023,4800.0,-0.20,NaN
1079,21,김건,한화,0.167,7,12,12,1,2,0,...,0.167,0.167,0.334,1,0.250,0.000,2023,3100.0,-0.35,3200.0
1080,13,장운호,한화,0.222,4,11,9,1,2,0,...,0.222,0.364,0.586,0,0.250,0.000,2023,5000.0,-0.08,NaN
1081,1,이재용,한화,0.500,2,2,2,1,1,0,...,0.500,0.500,1.000,0,0.000,0.000,2023,3100.0,0.04,3100.0

In [330]:
hitter_salary_stats_all = hitter_salary_stats.dropna(subset=['후년연봉','연봉(만원)','WAR']).reset_index(drop=True)

In [331]:
salary['팀명'].unique()

array(['KIA', '삼성', '두산', 'SSG', 'LG', '롯데', '한화', 'NC', 'KT', '키움'],
      dtype=object)

In [332]:
hitter_salary_stats_all

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
0,7,터커,KIA,0.306,142,631,542,100,166,40,...,0.557,0.398,0.955,44,0.300,0.000,2020,55000.0,3.46,70000.0
1,21,박찬호,KIA,0.223,141,531,480,63,107,16,...,0.275,0.276,0.551,30,0.185,0.000,2020,10500.0,-0.77,10000.0
2,2,최형우,KIA,0.354,140,600,522,93,185,37,...,0.590,0.433,1.023,55,0.374,1.000,2020,150000.0,6.59,90000.0
3,8,나지완,KIA,0.291,137,556,468,73,136,19,...,0.444,0.392,0.836,32,0.338,0.250,2020,60000.0,2.01,40000.0
4,13,유민상,KIA,0.246,126,456,391,38,96,23,...,0.366,0.341,0.707,15,0.308,0.273,2020,6000.0,-0.25,10500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,23,유로결,한화,0.146,27,53,48,5,7,1,...,0.167,0.173,0.340,1,0.125,0.000,2023,3300.0,-0.45,3300.0
814,26,하주석,한화,0.114,25,38,35,4,4,1,...,0.143,0.184,0.327,0,0.167,0.200,2023,10000.0,-0.58,7000.0
815,20,이명기,한화,0.175,14,42,40,2,7,1,...,0.200,0.214,0.414,2,0.200,0.000,2023,5000.0,-0.29,5000.0
816,21,김건,한화,0.167,7,12,12,1,2,0,...,0.167,0.167,0.334,1,0.250,0.000,2023,3100.0,-0.35,3200.0
817,1,이재용,한화,0.500,2,2,2,1,1,0,...,0.500,0.500,1.000,0,0.000,0.000,2023,3100.0,0.04,3100.0

In [333]:
# 중복 제거
hitter_salary_stats_all.drop_duplicates(inplace=True)

## 4.4. 최종 데이터 확인 및 저장

In [334]:
hitter_salary_stats_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      818 non-null    int64
 1   선수명     818 non-null    object
 2   팀명      818 non-null    object
 3   AVG     818 non-null    float64
 4   G       818 non-null    int64
 5   PA      818 non-null    int64
 6   AB      818 non-null    int64
 7   R       818 non-null    int64
 8   H       818 non-null    int64
 9   2B      818 non-null    int64
 10  3B      818 non-null    int64
 11  HR      818 non-null    int64
 12  TB      818 non-null    int64
 13  RBI     818 non-null    int64
 14  SAC     818 non-null    int64
 15  SF      818 non-null    int64
 16  BB      818 non-null    int64
 17  IBB     818 non-null    int64
 18  HBP     818 non-null    int64
 19  SO      818 non-null    int64
 20  GDP     818 non-null    int64
 21  SLG     818 non-null    float64
 22  OBP     818 non-null    float64
 23  OPS     818 non-null    float64
 24  MH      818 non-null    int64
 25  RISP    818 non-null    float64
 26  PH-BA   818 non-null    float64
 27  연도      818 non-null    int64
 28  연봉(만원)  818 non-null    float64
 29  WAR     818 non-null    float64
 30  후년연봉    818 non-null    float64
dtypes: float64(9), int64(20), object(2)
memory usage: 198.2+ KB

In [335]:
hitter_salary_stats_all.groupby('팀명').count()

,순위,선수명,AVG,G,PA,AB,R,H,2B,3B,...,SLG,OBP,OPS,MH,RISP,PH-BA,연도,연봉(만원),WAR,후년연봉
팀명,,,,,,,,,,,,,,,,,,,,,
KIA,90,90,90,90,90,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
KT,82,82,82,82,82,82,82,82,82,82,...,82,82,82,82,82,82,82,82,82,82
LG,74,74,74,74,74,74,74,74,74,74,...,74,74,74,74,74,74,74,74,74,74
NC,78,78,78,78,78,78,78,78,78,78,...,78,78,78,78,78,78,78,78,78,78
SSG,85,85,85,85,85,85,85,85,85,85,...,85,85,85,85,85,85,85,85,85,85
두산,88,88,88,88,88,88,88,88,88,88,...,88,88,88,88,88,88,88,88,88,88
롯데,75,75,75,75,75,75,75,75,75,75,...,75,75,75,75,75,75,75,75,75,75
삼성,85,85,85,85,85,85,85,85,85,85,...,85,85,85,85,85,85,85,85,85,85
키움,84,84,84,84,84,84,84,84,84,84,...,84,84,84,84,84,84,84,84,84,84
한화,77,77,77,77,77,77,77,77,77,77,...,77,77,77,77,77,77,77,77,77,77

In [336]:
hitter_salary_stats_all.to_csv('hitter_salary_stats_all.csv',index=False)

In [342]:
salary[salary['선수명'] == '김동혁']

      선수명    연도  팀명  연봉(만원)   WAR  후년연봉
811   김동혁  2020  키움    2700  0.11  2700
1654  김동혁  2021  키움    3000  0.44  3000
2450  김동혁  2022  키움    6000  0.13  6000
2989  김동혁  2023  롯데    3000  0.03  3000
3315  김동혁  2023  키움    6500 -0.46  6500
3857  김동혁  2024  롯데    3100  0.42  3100
4145  김동혁  2024  키움    6000 -0.24  6000